name: ERP DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r req.txt

      - name: Run basic test
        run: |
          python -m py_compile app.py

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "sakshicloud77" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t sakshicloud77/erp-app:latest .
          docker push sakshicloud77/erp-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.60.229.246
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker rm -f erp-app || true
            docker rmi sakshicloud77/erp-app:latest || true
            docker pull sakshicloud77/erp-app:latest
            docker run -d -p 80:5000 --name erp-app sakshicloud77/erp-app:latest
