name: ERP DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r req.txt

      - name: Run basic test
        run: |
          python -m py_compile app.py

      - name: Build Docker image
        run: |
          docker build -t erp-app .
